spring.application.name=sosyalizbiz-backend

spring.datasource.url=jdbc:postgresql://sosyalizbiz-postgres:5432/sosyalizbizdb?sslmode=require
spring.datasource.username=postgresuser
spring.datasource.password=postgrespass
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect