spring.application.name=sosyalizbiz-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/sosyalizbizdb
spring.datasource.username=postgresuser
spring.datasource.password=postgrespass
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=1020963521700-gnd8aftq1lf7ajmkr46vgljsjgiirqla.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.mail.username=deneme@gmail.com
spring.mail.password=mailapppassword